[WIP] 弾クラスの作成＆描画
human-osaka-game-2018/Shooting pull request #12
Opened 2019-02-23 14:56 UTC by yahara-mitsuaki

- [ ] 弾クラスの作成

- [ ] 弾の描画

2019-02-28 15:05 UTC, taishi-matsumura requested changes

2019-02-28 15:05 UTC, taishi-matsumura commented on Shooting/Shooting/Bullet/Bullet.cpp
> +Bullet::Bullet(POSITION pPlayePosition)
仮引数、ポインタじゃないので
```suggestion
Bullet::Bullet(POSITION playePosition)
```
では？

2019-02-28 15:05 UTC, taishi-matsumura commented on Shooting/Shooting/Global.cpp
> +void SetCustomvertex(CUSTOMVERTEX* pCustomvertex, POSITION position, float rightTU, float bottomTV, float leftTU, float topTV)
```suggestion
void SetCustomVertex(CUSTOMVERTEX* pCustomVertex, POSITION position, float rightTU, float bottomTV, float leftTU, float topTV)
```
では？

2019-02-28 15:05 UTC, taishi-matsumura commented on Shooting/Shooting/Player/Player.cpp
>  		if (diks[DIK_RIGHT] & 0x80)
辻野が川原に指摘していましたが、キー押下の判定関数作りましょう。
理由は [StarLight_Lineのプルリク](https://github.com/human-osaka-game-2018/StarLight_Line/pull/1) の `Mouse.cpp` や `Keyboard.cpp` への指摘を見て下さい。

2019-02-28 15:05 UTC, taishi-matsumura commented on Shooting/Shooting/Player/Player.cpp
>  		}
似て非なるコードが入り乱れているので、関数化してしまった方が良いと思います。

* x軸方向に動かす関数とy軸方向に動かす関数に分ける
* 画面外に出たら戻す関数を作る

とか、
* 移動関数を上下左右4つ作り、はみ出たときに戻す処理はそいつらの中でやる

とか、色々考えられると思います。

いずれにせよ目的は、 `Control()` の中身を「各キーの押下状態をチェックし、キーが押されていたらその方向に動かす」というレベルに抽象化することです。
そのために、「`m_Pos.y`に`m_MovmentAmount`を加えて…」といった細かい具体的な処理を `Control()` の外に追い出したいのです。

2019-02-28 15:05 UTC, taishi-matsumura commented on Shooting/Shooting/Player/Player.cpp
> +			if (1280 <= (m_Pos.x + m_Pos.XScale))
マジックナンバー、なんとかして下さい。

2019-02-28 15:05 UTC, taishi-matsumura commented on Shooting/Shooting/Player/Player.h
> +	inline POSITION getPos()
こういう、メンバ変数に変更を与えない関数はconst関数にしてしまいましょう。
少しずつやっていけば良いですよ。

2019-02-28 15:05 UTC, taishi-matsumura commented on Shooting/Shooting/Bullet/Bullet.cpp
> +void Bullet::render(IDirect3DDevice9* pD3Device, IDirect3DTexture9** pTexture)
必要なのは弾のテクスチャオブジェクトだけで他のテクスチャは要らないですよね。
だったら配列ごっそり貰う必要無いのでは？

2019-02-28 15:05 UTC, taishi-matsumura commented on Shooting/Shooting/Player/Player.h
>  	int counter;
こいつらにはプレフィックス付けないのですか？

2019-02-28 15:05 UTC, taishi-matsumura commented on Shooting/Shooting/Player/Player.cpp
> +void Player::render(IDirect3DDevice9* pD3Device, IDirect3DTexture9** pTexture)
メソッド名、PascalCaseとLowerCamelが入り乱れているので統一して下さい。

2019-02-28 15:08 UTC, taishi-matsumura commented
コミットが細かく分けられていて、しかもコミットメッセージを読めばそのコミットでの変更内容がわかるので、とてもレビューしやすかったです 👏 
この調子で継続して下さい！！ 💪

2019-02-28 16:30 UTC, taishi-matsumura commented
どのIssueに紐付くプルリクなのかをdescriptionに書いておいて下さい。
このプルリクがマージされたときにIssueを閉じちゃって良ければ `Closes #番号` 、まだ閉じたらダメなら `Refs #番号` と書いておけば、このプルリクから参照されている旨がIssue側に追記されるので後から追い掛けやすいです。(というか、そうしないと後から追えない)

2019-03-01 14:42 UTC, yahara-mitsuaki commented on Shooting/Shooting/Bullet/Bullet.cpp
> +Bullet::Bullet(POSITION pPlayePosition)
弾クラスのコンストラクタ変更で直しました

2019-03-01 14:43 UTC, yahara-mitsuaki commented on Shooting/Shooting/Bullet/Bullet.cpp
> +void Bullet::render(IDirect3DDevice9* pD3Device, IDirect3DTexture9** pTexture)
弾の描画関数の変更で直しました

2019-03-01 14:52 UTC, yahara-mitsuaki commented on Shooting/Shooting/Player/Player.cpp
> +void Player::render(IDirect3DDevice9* pD3Device, IDirect3DTexture9** pTexture)
どこかにルールをまとめえおきたいのですが、ハップハザードみたいにwikiにまとめるのがいいですか？

2019-03-01 14:53 UTC, taishi-matsumura commented on Shooting/Shooting/Player/Player.cpp
> +void Player::render(IDirect3DDevice9* pD3Device, IDirect3DTexture9** pTexture)
そだね

2019-03-01 14:53 UTC, taishi-matsumura commented on Shooting/Shooting/Player/Player.cpp
> +void Player::render(IDirect3DDevice9* pD3Device, IDirect3DTexture9** pTexture)
そだね

2019-03-01 14:59 UTC, yahara-mitsuaki commented
- キー押下の判定関数作成
- 移動処理関数の作成
- マジックナンバーのラッピング
- const関数化
- プレイヤークラスのメンバにプレフィックスつける
- 関数名の統一
以上の修正は内容がこのプルリクと関係ないので別プルリクでします

2019-03-01 14:59 UTC, taishi-matsumura commented on Shooting/Shooting/main.cpp
>  	player.render(g_pD3Device, g_pTexture);
こっちはまた別プルリクで直しましょうか。

2019-03-01 15:01 UTC, taishi-matsumura commented on Shooting/Shooting/Player/Player.cpp
> +void Player::render(IDirect3DDevice9* pD3Device, IDirect3DTexture9** pTexture)
[こんな感じ](https://github.com/human-osaka-game-2016/T-SEN/wiki) かな？

2019-03-01 15:13 UTC, taishi-matsumura commented
> * キー押下の判定関数作成
> * 移動処理関数の作成
> * マジックナンバーのラッピング
> * const関数化
> * プレイヤークラスのメンバにプレフィックスつける
> * 関数名の統一
>   以上の修正は内容がこのプルリクと関係ないので別プルリクでします

了解です。では、プルリク作って下さい。
各プルリクのdescriptionには、紐付くIssueへの参照と併せて `プルリクエスト #12 での指摘事項` みたいな感じの説明を書いておいて下さいね。

コミットの整理とプルリク作成が完了したらmasterにマージしますので連絡下さい。

2019-03-01 15:21 UTC, taishi-matsumura commented
> コミットの整理とプルリク作成が完了したらmasterにマージしますので連絡下さい。

あああーーー！！！
その前に、このブランチから枝分かれしている「複数発射」の枝をここの最新にrebaseしておかないと酷いことになるわ。

2019-03-01 15:23 UTC, taishi-matsumura commented
と思ったけど、あっちは空コミットだけか。
じゃあ大丈夫やわ。

2019-03-01 15:36 UTC, yahara-mitsuaki commented
> 各プルリクのdescriptionには、紐付くIssueへの参照と併せて `プルリクエスト #12 での指摘事項` みたいな感じの説明を書いておいて下さいね。
> 
> コミットの整理とプルリク作成が完了したらmasterにマージしますので連絡下さい。
紐づくissueは新しく作ったほうがいいですか？プレイヤーに関しては閉じたものがあるのですがそっちに紐づけると見づらいですか？

2019-03-01 15:39 UTC, taishi-matsumura commented
うわ、八原のコメントを修正してしまった。

2019-03-01 15:48 UTC, yahara-mitsuaki commented on Shooting/Shooting/Player/Player.cpp
> +void Player::render(IDirect3DDevice9* pD3Device, IDirect3DTexture9** pTexture)
大半が流用ですが作ってみました

2019-03-01 16:10 UTC, taishi-matsumura commented on Shooting/Shooting/Player/Player.cpp
> +void Player::render(IDirect3DDevice9* pD3Device, IDirect3DTexture9** pTexture)
リンク書くときは
```
[表示用文字列](URL)
```
ですね。

大半が流用ですが[作ってみました](
https://github.com/human-osaka-game-2018/Shooting/wik)。

みたいな感じ。

2019-03-01 16:47 UTC, yahara-mitsuaki commented
プルリク作成が完了したので確認お願いします

2019-03-01 16:58 UTC, taishi-matsumura commented
はい、確認しました。
`git rebase -i` 使ってコミット整理しちゃって下さい。

vimの画面が見辛かったら、ターミナルのタイトル領域で右クリック→オプション→テキスト のところでフォント変えたりフォントサイズ変えたりできます。
等幅フォントに変えとくと見易いですよ。
僕のオススメは [Myrica](https://myrica.estable.jp) です。

2019-03-01 17:47 UTC, yahara-mitsuaki commented
コミット整理ってどうやるんですか？
[これ](https://www.wakuwakubank.com/posts/382-git-rebase/)やってみたんですがログ出した後コマンド打てなくて泣

2019-03-01 18:01 UTC, taishi-matsumura commented
あ、初めてか。
じゃあ、整理作業は誰かと一緒にやれば良いので、その前にSourceTreeからターミナル開いて vimtutor って打ってvimの練習しといて下さい。

2019-03-02 03:52 UTC, yahara-mitsuaki commented
コミットメッセージまとめたので確認おねがいします

2019-03-02 09:41 UTC, taishi-matsumura approved these changes

2019-03-02 09:43 UTC, merged