基礎構築
human-osaka-game-2018/Shooting pull request #16
Opened 2019-03-01 16:42 UTC by yahara-mitsuaki

Close #14
プルリクエスト #12 での指摘事項
- キー押下の判定関数作成

- マジックナンバーのラッピング

- 関数名の統一

2019-03-01 18:20 UTC, yahara-mitsuaki commented
DirectInputクラスを作ってそこにキーの判定関数を入れるように変更

2019-03-02 18:00 UTC, yahara-mitsuaki commented
完了したのでレビューお願いします

2019-03-03 09:25 UTC, taishi-matsumura requested changes
今回もレビューしやすかったです。この調子でお願いします 💪 

修正依頼と質問をいくつか書いたので、それぞれ回答お願いします。

2019-03-03 09:25 UTC, taishi-matsumura commented on Shooting/Shooting/DirectInput/DirectInput.cpp
> +void DirectInput::AcquireInputState()
「キーボード入力の状態を取得する関数」の名前としては適当では無いです。
`IDirectInputDevice8::Acquire()` は入力デバイスへのアクセス権を取得する関数であって、キーの状態を取得する関数ではありません。

2019-03-03 09:25 UTC, taishi-matsumura commented on Shooting/Shooting/DirectInput/DirectInput.cpp
> +		m_pKeyDevice->GetDeviceState(sizeof(m_diks), m_diks);
ここで `sizeof(m_diks)` って書いたら `4` が返ってきませんか？
ちゃんと期待通り `256` が返ってくるのなら問題ありません。

2019-03-03 09:25 UTC, taishi-matsumura commented on Shooting/Shooting/DirectInput/DirectInput.cpp
> +	return (m_diks[key] & 0x80);
C/C++的には問題無い書き方ですが(むしろC/C++っぽい)、他の言語だとコンパイルエラーになることの方が多いというのは知っておいて下さい。

2019-03-03 09:25 UTC, taishi-matsumura commented on Shooting/Shooting/DirectInput/DirectInput.h
> +	bool IsKeyPressed(int key);
こいつの引数のように「型はintなんだけど、実際は `DIK_XXX` の中から選んで指定しなければ動作しない」みたいなやつはコメント必須でしょうね。
コメントは後から書く予定なんだと思っていますが、その時には注意して下さいね。

2019-03-03 09:25 UTC, taishi-matsumura commented on Shooting/Shooting/DirectInput/DirectInput.cpp
> +		DIRECTINPUT_VERSION, IID_IDirectInput8, (VOID**)&m_pDinput, NULL)))
`m_pDinput` は、いつ・誰が解放するのですか？

2019-03-03 09:25 UTC, taishi-matsumura commented on Shooting/Shooting/DirectInput/DirectInput.cpp
> +	if (FAILED(hr = m_pDinput->CreateDevice(GUID_SysKeyboard, &m_pKeyDevice, NULL)))
`m_pKeyDevice` は、いつ・誰が解放するのですか？

2019-03-03 10:36 UTC, taishi-matsumura commented on Shooting/Shooting/DirectInput/DirectInput.cpp
> +		m_pKeyDevice->GetDeviceState(sizeof(m_diks), m_diks);
テストコード書いてみましたが、ちゃんと配列の要素数が取れるみたいですね。
ダメなのは関数の引数で受け取った配列(の先頭アドレス)に対して `sizeof` 演算子でサイズ求めるときか。
自己解決です。すみません。

2019-03-04 08:07 UTC, yahara-mitsuaki commented on Shooting/Shooting/DirectInput/DirectInput.cpp
> +void DirectInput::AcquireInputState()
`AcquireInputState()`の機能としては`GetDeviceState()`の部分が主幹なのでこの名前にしました。

2019-03-04 11:00 UTC, taishi-matsumura commented on Shooting/Shooting/DirectInput/DirectInput.cpp
> +void DirectInput::AcquireInputState()
参考にしたソースがそのような命名になっていたのですね。経緯、理解しました。

先程口頭で伝えましたが、
* 「アクセス権を取得する」という意味の `Acquire` が既に存在している上にこの関数の中でも呼び出していること
* 自身でも認識している通り、 `GetDeviceState()` でデバイスの状態を取得することがこの関数の機能の主幹であること

から、「 `AcquireInputState()`  という命名は不適切では？」というのが私の指摘の内容です。
`GetKeyState` とかが妥当ではないでしょうか。

2019-03-05 06:26 UTC, yahara-mitsuaki commented
修正したので確認お願いします

2019-03-05 07:22 UTC, taishi-matsumura commented on Shooting/Shooting/DirectInput/DirectInput.cpp
> +	}
`==` や `!=` の結果は(普通は)booleanなので、
```
return (m_diks[key] & 0x80 != 0);
```
で良いと思います。

2019-03-05 07:22 UTC, taishi-matsumura commented on Shooting/Shooting/DirectInput/DirectInput.cpp
> +void DirectInput::AcquireInputState()
ごめん、「キーの状態を返す関数」じゃないんやね…
「そのフレームでの全てのキーの状態をチェックして保存する関数」なんですね。
だったら `CaptureKeyState()` とかどうでしょう？
振り回してすみません。

2019-03-05 07:30 UTC, taishi-matsumura requested changes

2019-03-05 07:30 UTC, taishi-matsumura commented on Shooting/Shooting/main.cpp
> +//HRESULT InitDinput(HWND hWnd);
コメントアウトするぐらいなら消してしまいましょうよ

2019-03-05 08:47 UTC, yahara-mitsuaki commented
修正したので確認お願いします

2019-03-05 16:56 UTC, taishi-matsumura commented
指摘是正、お疲れ様でした 🍵 
コミットをいい感じに纏めてくれたらマージしま〜す

2019-03-06 03:40 UTC, yahara-mitsuaki commented
コミットまとめたので確認お願いします

2019-03-06 10:48 UTC, taishi-matsumura commented
あーあ、せっかく綺麗な細かいコミット作ってたのに一言でまとめちゃったなぁ。
後から「[issue #14] DirectInputクラス作成」ってコミットメッセージを見たときに、このプルリクでやった内容を思い出せるのなら良いのですが…
個人的にはその点については懐疑的ですが、まぁ本人が大丈夫と言うのなら良いのでしょう。

2019-03-06 10:49 UTC, taishi-matsumura approved these changes

2019-03-06 10:49 UTC, merged

2019-03-07 01:19 UTC, yahara-mitsuaki commented
> あーあ、せっかく綺麗な細かいコミット作ってたのに一言でまとめちゃったなぁ。
> 後から「[issue #14] DirectInputクラス作成」ってコミットメッセージを見たときに、このプルリクでやった内容を思い出せるのなら良いのですが…
> 個人的にはその点については懐疑的ですが、まぁ本人が大丈夫と言うのなら良いのでしょう。

次からは詳細の部分にログとして残すようにしてみます